service: api-tts

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  profile: ${env:PROFILE_NAME, 'default'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "bedrock:InvokeModel"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/CadastroIdosos"
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/CadastroVoluntarios"
        - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${env:DYNAMODB_TABLE}"
    - Effect: "Allow"
      Action:
        - "polly:SynthesizeSpeech"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "comprehend:DetectDominantLanguage"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lex:PostText"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lex:RecognizeText"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "transcribe:StartTranscriptionJob"
        - "transcribe:GetTranscriptionJob"
        - "transcribe:ListTranscriptionJobs"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
  deploymentBucket:
    name: ${env:S3_BUCKET_NAME}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

resources:
  Resources:
    CadastroIdosos:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "CadastroIdosos"
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    CadastroVoluntarios:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "CadastroVoluntarios"
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

functions:
  health:
    name: lacfas-health-function
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
          
  v1Description:
    name: lacfas-v1-description-function 
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get

  v1_tts:
    name: lacfas-v1-tts-function 
    handler: post.lambda_handler
    events:
      - httpApi:
          path: /v1/tts
          method: post

  cadastrarIdoso:
    handler: handler.persist_idoso
    events:
      - httpApi:
          path: /cadastrar_idoso
          method: post

  cadastrarVoluntario:
    handler: handler.persist_voluntario
    events:
      - httpApi:
          path: /cadastrar_voluntario
          method: post

  generateDynamicQuestion:
    handler: handler.generate_dynamic_question_handler
    events:
      - httpApi:
          path: /generate-question
          method: post

  processSlackMessage:
    handler: slackHandler.lambda_handler
    events:
      - httpApi:
          path: /slack/events
          method: post
    environment:
      S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

  transcribeAudio:
    name: lacfas-v1-transcribe-function
    handler: utils.transcribe_audio.transcribe_audio_handler
    events:
      - httpApi:
          path: /v1/transcribe
          method: post
